import { TableColumnOptions } from 'typeorm';

export enum TeamUserRole {
    DEVELOPER = 'developer',
    TESTER = 'tester',
    PROJECTMANAGER = 'project manager',
    INFRA = 'infra',
    ACCOUNTING = 'accounting',
}

export enum TABLE_NAME {
    Users = 'users',
    Files = 'files',
    Candidates = 'candidates',
    Teams = 'teams',
    GeneralSettings = 'general_settings',
    CandidateInterviews = 'candidate_interviews',
    CandidateEmail = 'candidate_emails',
    DeviceTypes = 'device_types',
    Assets = 'asset',
    Roles = 'roles',
    Provinces = 'provinces',
    UserLogging = 'user_logging',
    Billings = 'billings',
    User_Tokens = 'user_tokens',
    Events = 'event',
    Contracts = 'contracts',
    TeamUsers = 'team_member',
    Timekeeping = 'timekeepings',
    RequestAssets = 'request_asset',
    RequestAbsences = 'request_absences',
    FingerScan = 'finger_scanner_data',
    UserPosition = 'user_position',
    Bank = 'banks',
    ContractTypes = 'contract_types',
    SettingHoliday = 'setting_holidays',
    PermissionActions = 'permission_actions',
    Permissions = 'permissions',
    PermissionResources = 'permission_resources',
    RolePermissions = 'role_permissions',
    CandidateInterviewHistories = 'candidate_interview_histories',
    Bookings = 'bookings',
    Categories = 'categories',
    Foods = 'foods',
    TablesRestaurants = 'tables_restaurants',
    Suppliers = 'suppliers',
    Materials = 'materials',
    ConvertHistories = 'convert_histories',
    ImportMaterials = 'import_materials',
    ImportMaterialOrders = 'import_material_orders',
    ExportMaterials = 'export_materials',
    ExportMaterialOrders = 'export_material_orders',
    CheckInventories = 'check_inventories',
    CheckInventoryDetails = 'check_inventory_details',
    ClosingRevenue = 'closing_revenue',
}

export const commonColumns: TableColumnOptions[] = [
    {
        name: 'id',
        type: 'int',
        isPrimary: true,
        isGenerated: true,
        generationStrategy: 'increment',
    },
    {
        name: 'createdAt',
        type: 'timestamp',
        default: 'CURRENT_TIMESTAMP',
        isNullable: true,
    },
    {
        name: 'updatedAt',
        type: 'timestamp',
        default: 'CURRENT_TIMESTAMP',
        isNullable: true,
    },
    {
        name: 'deletedAt',
        type: 'timestamp',
        isNullable: true,
    },
    {
        name: 'createdBy',
        type: 'int',
        isNullable: true,
    },
    {
        name: 'updatedBy',
        type: 'int',
        isNullable: true,
    },
    {
        name: 'deletedBy',
        type: 'int',
        isNullable: true,
    },
];

export enum DBPermissionActions {
    READ = 'read',
    CREATE = 'create',
    UPDATE = 'update',
    DELETE = 'delete',
    LOGIN = 'login',
    UPDATE_ROLE = 'update_role',
    CONVERT_MATERAL = 'convert_material',
}

export enum DBPermissionResources {
    DASHBOARD = 'dashboard',
    USER = 'user',
    TABLE_DIAGRAM = 'tableDiagram',
    BOOKING = 'booking',
    MENU_FOOD = 'food',
    MENU_CATEGORY = 'category',
    STORE_MATERIAL = 'storeMaterial',
    STORE_CONVERT = 'storeConvert',
    STORE_SUPPLIER = 'storeSupplier',
    STORE_IMPORT_MATERIAL = 'StoreImportMaterial',
    STORE_IMPORT_MATERIAL_DETAIL = 'StoreImportMaterialDetail',
    STORE_EXPORT = 'StoreExport',
    STORE_EXPORT_MATERIAL_DETAIL = 'StoreExportMaterialDetail',
    STORE_CHECK_INVENTORY = 'StoreCheckInventory',
    STORE_INVENTORY_DETAIL = 'StoreInventoryDetail',
    BILLING = 'billing',
    CLOSING_REVENUE = 'closingRevenue',
    ROLE = 'role',
}
