import { MigrationInterface, QueryRunner } from 'typeorm';
import { TABLE_NAME } from '../constant';

export class SeedingTablesRestaurant1720963593404
    implements MigrationInterface
{
    public async up(queryRunner: QueryRunner): Promise<void> {
        const tables = [
            {
                name: '1-1',
                status: 'booked',
                numberSeat: 1,
                nameCustomer: 'ahihi',
                phone: '123123',
                arrivalTime: '2022-04-20 17:00:00',
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-2',
                status: 'booked',
                numberSeat: 2,
                nameCustomer: 'huhuhu',
                phone: '69369369',
                arrivalTime: '2022-04-20 17:00:00',
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-3',
                status: 'ready',
                numberSeat: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-4',
                status: 'ready',
                numberSeat: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-5',
                status: 'used',
                numberSeat: 6,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-6',
                status: 'ready',
                numberSeat: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-7',
                status: 'ready',
                numberSeat: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-8',
                status: 'used',
                numberSeat: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-9',
                status: 'ready',
                numberSeat: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-10',
                status: 'ready',
                numberSeat: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-11',
                status: 'ready',
                numberSeat: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-12',
                status: 'ready',
                numberSeat: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-13',
                status: 'ready',
                numberSeat: 6,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-14',
                status: 'ready',
                numberSeat: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-15',
                status: 'ready',
                numberSeat: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-16',
                status: 'ready',
                numberSeat: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '2-1',
                status: 'ready',
                numberSeat: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '2-2',
                status: 'ready',
                numberSeat: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '2-3',
                status: 'ready',
                numberSeat: 6,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '2-4',
                status: 'ready',
                numberSeat: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '3-1',
                status: 'ready',
                numberSeat: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '3-2',
                status: 'ready',
                numberSeat: 6,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '3-3',
                status: 'ready',
                numberSeat: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '3-4',
                status: 'ready',
                numberSeat: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '4-1',
                status: 'ready',
                numberSeat: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
        ];
        await queryRunner.manager
            .getRepository(TABLE_NAME.TablesRestaurants)
            .insert(tables);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.manager
            .getRepository(TABLE_NAME.TablesRestaurants)
            .delete({});
    }
}
